### ISSUE TITLE
ToDo CLI commands

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/som#13]
CLI commands required for basic usage:

- [x] `train` trains an SOM from a table
- [x] `label` for semi-supervised label propagation
- [x] `export` exports an SOM to a table of node vectors
- [x] `bmu` finds the best-matching unit for each row in a table
- [x] `predict` predicts one or more layers from other layers
- [x] `fill-missing` fills missing data in a table using an SOM
- [x] `plot` for platting an SOM
   - [x] `heatmap`
   - [x] `u-matrix`
   - [x] `density`
   - [x] `error`
   - [x] `xy`
   - [x] `codes`
      - [x] `line`
      - [x] `pie`
      - [x] `rose`
      - [x] `image`
